//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Globalization.Resources.CultureInfo.Properties
{
    
    internal partial class it
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((it.manager == null))
                {
                    it.manager = new System.Resources.ResourceManager("System.Globalization.Resources.CultureInfo.Properties.it", typeof(it).Assembly);
                }
                return it.manager;
            }
        }
    }
}
