//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3D_control_v09
{
    
    internal partial class ResGUI
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((ResGUI.manager == null))
                {
                    ResGUI.manager = new System.Resources.ResourceManager("_3D_control_v09.ResGUI", typeof(ResGUI).Assembly);
                }
                return ResGUI.manager;
            }
        }
        internal static Microsoft.SPOT.Bitmap GetBitmap(ResGUI.BitmapResources id)
        {
            return ((Microsoft.SPOT.Bitmap)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static Microsoft.SPOT.Font GetFont(ResGUI.FontResources id)
        {
            return ((Microsoft.SPOT.Font)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static string GetString(ResGUI.StringResources id)
        {
            return ((string)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            WinWaitingScreen = -30040,
            WinStop = -26443,
            WinLanguageChange = -26058,
            WinShutDown = -25410,
            WinMain = -19953,
            WinCutChangeSelector = -11005,
            WinInfo = -3949,
            WinSettingsTemp = -808,
            WinSettingsAnother = 1032,
            WinPausePrint = 3032,
            WinModel = 4851,
            WinSettingOffset = 6544,
            WinPreheater = 8533,
            WinCutChange = 9906,
            WinTestServo = 12842,
            WinSettings = 21167,
            WinError = 21603,
            WinCutChangeStoliceDGR = 22546,
            WinPrintInfo = 30448,
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            ubuntu_medium_16_utf8 = -19280,
            ubuntu_bold_20_utf8 = -7730,
            ubuntu_bold_17_utf8 = 16269,
        }
        [System.SerializableAttribute()]
        internal enum BitmapResources : short
        {
            logo1 = -9350,
        }
    }
}
