//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3D_control_v09
{
    
    internal partial class Resources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resources.manager == null))
                {
                    Resources.manager = new System.Resources.ResourceManager("_3D_control_v09.Resources", typeof(Resources).Assembly);
                }
                return Resources.manager;
            }
        }
        internal static string GetString(Resources.StringResources id)
        {
            return ((string)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static byte[] GetBytes(Resources.BinaryResources id)
        {
            return ((byte[])(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            TextOpenDoorOrCover = -31815,
            scrSettingOffsetBtReload = -31141,
            scrSettingTempTxMain = -31089,
            scrPreheatTx7 = -30504,
            scrPreheatTx6 = -30503,
            scrPreheatTx1 = -30502,
            scrPreheatTx2 = -30499,
            scrPreheatTx5 = -30490,
            scrPreheatTx4 = -30489,
            scrCutInsertPrimaryFil = -30428,
            TextNext = -29970,
            scrShutDownTx4 = -29890,
            TextContinePrintingFromOffState = -29486,
            scrSettingBtAnother = -29481,
            TextErrorStopMove = -29323,
            TextCeilingOpen = -28688,
            TextStartPrint = -27621,
            scrPreheatBtOn = -27603,
            Text3DmodelFalse = -26864,
            TextPrevious = -26823,
            TextDataTransferText = -25652,
            TextDoorOpen = -25275,
            TextFinish = -24238,
            TextRepeat = -24157,
            scrSettingTempSpace = -23920,
            scrCutIncorectChangeFil = -23197,
            scrInfoNameTraffic = -22914,
            scrModelBtPreheat = -22446,
            scrInfoTrafficTime = -21558,
            TextStatePrintInit = -20555,
            scrModelBtPrint = -20071,
            scrSettingTxMain = -18455,
            TextNoModelSelection = -18368,
            TextNoMaterial = -17801,
            scrShutDownTx5 = -17411,
            TextError = -17136,
            TextSocketLittleFilament = -15884,
            TextStatePrintDone = -15720,
            scrShutDownTxMain = -15517,
            scrModelTxMain = -14739,
            TextYes = -14369,
            scrPreheatBtOff = -14165,
            scrtInfoTxMain = -13027,
            scrCutFlowsFilFromNozzle = -12458,
            TextDataTransferMain = -12375,
            scrPreheatTxStateOn = -12134,
            scrMainBtSetting = -11880,
            scrPauseTxInfo = -10505,
            TextRemove = -9873,
            scrStopTx2 = -9113,
            scrSettingTempNozzle = -8281,
            scrSettingAnotherBtOffset = -7903,
            TextCorrectSaveParam = -7504,
            scrInfoTypeProduct = -7496,
            TextStatePrintChangeString = -6750,
            TextEnd = -6706,
            scrPrintInfoTx5 = -6592,
            scrPrintInfoTx4 = -6591,
            scrPrintInfoTx3 = -6566,
            scrPrintInfoTx2 = -6565,
            scrPrintInfoTx1 = -6564,
            scrSettingAnotherTxMain = -6253,
            TextNo = -6222,
            scrStopTx4 = -5752,
            scrPreheatTxMain = -5699,
            srcInfoFirmware = -4537,
            TextPause = -2757,
            scrSettingAnotherBtTemper = -2240,
            srcInfoUrlWeb = -1895,
            scrCutExchangeDone = -1534,
            scrMainTxMain = -915,
            scrCatGutChTxMain = -457,
            scrPauseBtStop = -372,
            TextFeedIn = -156,
            TextTransferFile = 349,
            scrMainBtInfo = 731,
            TextStatePrintPause = 1372,
            scrSettingBtChange = 1658,
            scrShutDownTx1 = 1767,
            scrSettingAnotherBtUpdate = 2221,
            scrInfoNameCompany = 3031,
            scrSettingBtCalibration = 4079,
            scrSettingOffsetTxMain = 4788,
            TextContinue = 6064,
            scrPauseTxMain = 8660,
            TextCancel = 10499,
            TextIgnore = 11636,
            scrSettingOffsetBtSave = 12011,
            scrCutPreparePrintHeating = 12925,
            TextStop = 13210,
            scrStopTx3 = 13269,
            TextNoSDCard = 13479,
            TextBack = 13503,
            scrSettingOffsetInfo1 = 13790,
            scrMaintBtShutDown = 14554,
            scrCutEjectPrimaryFil = 14915,
            scrSettingAnotherBtTestAxis = 15699,
            TextSocketFalseFilament = 16647,
            TextStateUpsTraffic = 17114,
            scrStopTxMain = 17414,
            TextStatePrintStop = 17749,
            TextNoMaterialExtr1 = 17908,
            TextNoMaterialExtr2 = 17911,
            scrCatGutChScr0Cat2 = 19188,
            scrCatGutChScr0Cat1 = 19189,
            scrMainBtPrint = 19949,
            scrStopTx1 = 21086,
            TextNoCorrectSaveParam = 21373,
            TextPausePrint = 21839,
            TextErrorStopPrinting = 22817,
            TextMotionTest = 23043,
            scrSettingAnotherBtState = 23371,
            scrPreheatTxStateOff = 23739,
            scrSettingBtPark = 24688,
            scrSettingTempBed = 25192,
            scrShutDownTx3 = 25970,
            scrLanguageTxMain = 26009,
            scrInfoNameProduct = 26187,
            TextUpdateFW = 26306,
            TextOk = 27199,
            scrCatGutChScr4Tx1 = 27746,
            scrCatGutChScr5Tx1 = 27773,
            scrCatGutChScr0Tx1 = 27878,
            scrCatGutChScr1Tx1 = 27905,
            scrCatGutChScr2Tx1 = 28068,
            scrCatGutChScr3Tx1 = 28103,
            TextStatePrintPrint = 28175,
            scrCutInsertSecundFil = 28220,
            scrShutDownTx2 = 28965,
            TextSDLoad = 29064,
            scrSettingAnotherBtLang = 29314,
            TextNoSdLoad = 29478,
            scrPrintInfoTxMain = 29526,
            scrCutEjectSecondFil = 30245,
            TextStopPrint = 31935,
        }
        [System.SerializableAttribute()]
        internal enum BinaryResources : short
        {
            logo1 = -9350,
        }
    }
}
